### ISSUE TITLE
Implement startup probe configuration for slow starting containers

### ISSUE THREAD

**Issue by onedr0p** [billimek/billimek-charts#100]
Appears Jackett and NZBHydra are still a culprit of slow start up times. From researching on the k8s docs we can implement a startupProbe which might solve my issue once and for all.

I'll just implement this on Jackett and NZBHydra2 as the others seem to be pretty quick at starting.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes

**Comment by onedr0p** [comment]
I will continue to debug before accepting this is actually needed :/

**Comment by onedr0p** [comment]
Apply probe configuration as such has allowed these services to come online and not crash:

```yaml
    probes:
      liveness:
        initialDelaySeconds: 300
        failureThreshold: 5
        timeoutSeconds: 10
      readiness:
        initialDelaySeconds: 300
        failureThreshold: 5
        timeoutSeconds: 10   
```

I will close this issue.
