### ISSUE TITLE
create chart for teslamate

### ISSUE THREAD

**Issue by billimek** [billimek/billimek-charts#101]
* See the [teslamate](https://github.com/adriankumpf/teslamate) repo
* container image for teslamate: [teslamate/teslamate](https://hub.docker.com/r/teslamate/teslamate) (multi-arch image)
* use the postgres subchart. See [concourse](https://github.com/concourse/concourse-chart) as an example implementation

**Comment by billimek** [comment]
Example `docker-compose.yml` for this.  Wouldn't need the mqtt or grafana thing as those should (IMO) be an external implementation.

```yaml
version: '3'

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=db
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    cap_drop:
      - all

  db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=secret
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=db
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:1.6
    restart: always
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
    teslamate-db:
    teslamate-grafana-data:
    mosquitto-conf:
    mosquitto-data:
```
