### ISSUE TITLE
Help: Issue with cloudflare-dyndns chart

### ISSUE THREAD

**Issue by onedr0p** [billimek/billimek-charts#105]
Sorry I am still a bit of a newbie working with Kubernetes and Charts. I am having an issue deploying this chart.

```txt
# cloudflare-dyndns-helm-values.txt
cloudflare:
  user: "$CLOUDFLARE_USER"
  token: "$CLOUDFLARE_APIKEY"
  zones: "$CLOUDFLARE_ZONES"
  hosts: "$CLOUDFLARE_HOSTS"
  record_types: "$CLOUDFLARE_RECORDTYPES"
```

```yaml
# cloudflare-dyndns.yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cloudflare-dyndns
  namespace: default
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: cloudflare-dyndns
  chart:
    repository: https://billimek.com/billimek-charts/
    name: cloudflare-dyndns
    version: 1.0.0
  values:
    image:
      repository: hotio/cloudflare-ddns
      tag: stable-47b759b
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 128Mi
  valueFileSecrets:
  - name: "cloudflare-dyndns-helm-values"
```

The chart has defined the env variables like so:

```yaml
...
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CF_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "cloudflare-dyndns.fullname" . }}
                  key: cloudflare-dyndns-user
            - name: CF_APIKEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "cloudflare-dyndns.fullname" . }}
                  key: cloudflare-dyndns-token
            - name: CF_ZONES
              valueFrom:
                secretKeyRef:
                  name: {{ template "cloudflare-dyndns.fullname" . }}
                  key: cloudflare-dyndns-zones
            - name: CF_HOSTS
              valueFrom:
                secretKeyRef:
                  name: {{ template "cloudflare-dyndns.fullname" . }}
                  key: cloudflare-dyndns-hosts
            - name: CF_RECORDTYPES
              value: "{{ .Values.cloudflare.record_types }}"
            - name: DETECTION_MODE
              value: "{{ .Values.cloudflare.detection_mode }}"
            - name: LOG_LEVEL
              value: "{{ .Values.cloudflare.log_level }}"
            - name: SLEEP_INTERVAL
              value: "{{ .Values.cloudflare.sleep_interval }}"
...
```

Do you think I should update the Chart to not use the `valueFrom.secretKeyRef`? It seems as though they can all just be regular values (see below) like since the `valueFileSecrets` will just drop them in.

```yaml
          env:
            - name: CF_USER
              value: "{{ .Values.cloudflare.user }}"
            - name: CF_APIKEY
              value: "{{ .Values.cloudflare.token }}"
            - name: CF_ZONES
              value: "{{ .Values.cloudflare.zones }}"
            - name: CF_HOSTS
              value: "{{ .Values.cloudflare.hosts }}"
            - name: CF_RECORDTYPES
              value: "{{ .Values.cloudflare.record_types }}"
            - name: DETECTION_MODE
              value: "{{ .Values.cloudflare.detection_mode }}"
            - name: LOG_LEVEL
              value: "{{ .Values.cloudflare.log_level }}"
            - name: SLEEP_INTERVAL
              value: "{{ .Values.cloudflare.sleep_interval }}"
```

Again sorry and thanks for your help!

**Comment by billimek** [comment]
In addition to the `cloudflare-dyndns-helm-values.txt` file, do you have a secret created named the same (`cloudflare-dyndns-helm-values`) in the same namespace?  You will need a secret with the `data` json containing a `values.yaml` key with a base64-encoded set of values data to be merged in.

See [this](https://docs.fluxcd.io/projects/helm-operator/en/latest/references/helmrelease-custom-resource.html#secrets) for a possible better way to go about doing this.

**Comment by onedr0p** [comment]
I do have secret there in the same namespace. I am just a little confused on how to mix secrets and the non-secret envVars.

Shouldn't the `name` property below be `cloudflare-dyndns-helm-values`? Or is that is what is interpolated?

```yaml
            - name: CF_HOSTS
              valueFrom:
                secretKeyRef:
                  name: {{ template "cloudflare-dyndns.fullname" . }}
```
