### ISSUE TITLE
Blocky RollingUpdate strategy

### ISSUE THREAD

**Issue by onedr0p** [billimek/billimek-charts#186]
@billimek what do you think about adding `RollingUpdate` for the deployments `strategy` for 0 downtime?

Maybe something like this can be added to the deployment

```yaml
strategy:
  type: RollingUpdate
  rollingUpdate:
     maxUnavailable: 25%
     maxSurge: 1
```

**Comment by billimek** [comment]
@onedr0p the default update strategy for Deployments is already RollingUpdate, so adding that to the Deployment template may not be necessary.

For example, from the deployed `blocky` deployment from this chart is the following:

```yaml
strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate
```
