### ISSUE TITLE
Integrate radarr-exporter into the Radarr chart

### ISSUE THREAD

**Issue by onedr0p** [billimek/billimek-charts#187]
I currently run radarr-exporter as a standard k8s deployment (see [here](https://github.com/onedr0p/k3s-gitops/blob/master/deployments/monitoring/radarr-exporter/radarr-exporter.yaml)) 

We could actually implement this into the chart (possible as sidecar?) and update the values to accept whether or not to turn these on, maybe like the following:

```yaml
metrics:
  enabled: true
  port: 9811
  apiKey: <secret>
```

I do maintain the following projects:
- https://github.com/onedr0p/sonarr-exporter
- https://github.com/onedr0p/radarr-exporter
