### ISSUE TITLE
Persistent Volume Claims of /downloads and /movies should be located on same volume with one pvc

### ISSUE THREAD

**Issue by abel408** [billimek/billimek-charts#222]
By default, radarr and sonarr are set to rename movies and create hardlinks. Hardlinks can only be created when both file locations are located on the same file system. Even though the /downloads and /movies PV could be from the same share, the container has two mount points and will not recognize that they are from the same system. Instead of creating hardlinks, radarr and sonarr will copy the file.

**Comment by billimek** [comment]
Hi @abel408, correct!  We have the [`extraExistingClaimMounts`](https://github.com/billimek/billimek-charts/blob/master/charts/sonarr/values.yaml#L142-L148) configuration option to help address this (also for radarr)

An example of the implementation is [here](https://github.com/billimek/k8s-gitops/blob/master/default/sonarr/sonarr.yaml#L30-L43):

```yaml
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        size: 2Gi
      downloads:
        enabled: false
      tv:
        enabled: false
      extraExistingClaimMounts:
        - name: media
          existingClaim: nfs-media-pvc
          mountPath: /media
          readOnly: false
```

It seems like we should still 'allow' someone to choose to have the different mounts for downloads and tv/movies.  What do you think?

**Comment by abel408** [comment]
Ahhh, thank you. I do agree with allowing different mount points, however, the chart by default will create a mount point for each and radarr and sonarr, by default, will use hardlinks so I think there is a bit of a discrepancy there. I would imagine the only reason someone would want a mount point for each would be if they are organizing things manually? I just learned the hard way that radarr and sonarr have been duplicating all my files and am now in the process of reorganizing :/. I have a feeling I'm not the only one.

**Comment by billimek** [comment]
@abel408 this is a good point, we should consider changing the default behavior.  Something different than the `extraExistingClaimMounts` would be necessary for the two charts because we won't have an existing claim to reference by default.

@onedr0p what do you think?  I think we would need to change the chart to collapse /downloads and /tv or /movies into a single PVC and allow folks to leverage extraExistingClaimMounts if they really want them separate.  We could bump the chart major version to indicate a breaking change.

**Comment by onedr0p** [comment]
@billimek do you think a single `media` volume is good instead of `downloads` and `tv` or `movies` ?

**Comment by billimek** [comment]
@onedr0p yeah, exactly!  Can you think of any downsides taking that approach?

**Comment by onedr0p** [comment]
@billimek maybe, my current deployments use media in existingVolumeClaims. Do you think that is a conflict?

```yml
    persistence:
      downloads:
        enabled: false
      tv:
        enabled: false
      extraExistingClaimMounts:
        - name: media
          existingClaim: nfs-media-pvc
          mountPath: /media
          readOnly: false
```

**Comment by billimek** [comment]
With the change we're discussing, yeah.  I see it as being something like this:

```yaml
    persistence:
      config:
        enabled: true
      media:
        enabled: true
        existingClaim: nfs-media-pvc
        subPath: /media
      extraExistingClaimMounts: <not needed now>
```

... which would be a 'breaking' change
