### ISSUE TITLE
Question about the use of existingClaim

### ISSUE THREAD

**Issue by windowsrefund** [billimek/billimek-charts#234]
hello,

I have setup nfs-server-provisioner and have created a pvc against some openebs-backed storage. However, dynamic volume creation (via the PVC) is not happening when I deploy the sonarr chart. I'm trying to understand why that might be the case? This is my values.yaml which I pass in via -f

```
timezone: America/New_York
image:
  tag: latest
persistence:
  config:
    storageClass: openebs-cstor-persist
    skipuninstall: true
  media:
    existingClaim: nfs-pvc
    skipuninstall: true
  extraExistingClaimMounts:
    - name: torrents
      mountPath: /torrents
      existingClaim: nfs-pvc
      readOnly: False

```
Is dynamic provisioning somehow disabled because I'm not using storageClasssName? That question is based off the comments from the default values.yaml though I can't see why it would be needed if I'm pointing to a PVC that already exists. Very interested in any feedback.
