### ISSUE TITLE
[home-assistant] Homeassistant fails to start with AppDaemon enabled

### ISSUE THREAD

**Issue by rwlove** [billimek/billimek-charts#248]
**Describe the bug**
I'm instantiating HASS in a kubernetes cluster using the following definition. https://github.com/billimek/billimek-charts/tree/master/charts/home-assistant
 
Homeassistant fails to start with AppDaemon enabled.

**A clear and concise description of what the bug is.**
Version of Helm and Kubernetes:
Helm: v3.2.1
Kubernetes: v1.18.2

What happened:
➜  kubernetes git:(master) ✗ kubectl -n homeassistant logs homeassistant-home-assistant-8ccc9d79-f22bk -c appdaemon 
2020-06-14 16:35:45.284536 INFO AppDaemon Version 3.0.5 starting
2020-06-14 16:35:45.284770 INFO Configuration read from: /conf/appdaemon.yaml
2020-06-14 16:35:45.286422 INFO AppDaemon: Starting Apps
2020-06-14 16:35:45.289228 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2020-06-14 16:35:45.329504 INFO AppDaemon: HASS: HASS Plugin Initializing
2020-06-14 16:35:45.329869 INFO AppDaemon: HASS: HASS Plugin initialization complete
2020-06-14 16:35:45.330040 INFO Starting Dashboards
2020-06-14 16:35:45.330182 WARNING ------------------------------------------------------------
2020-06-14 16:35:45.330251 WARNING Unexpected error during run()
2020-06-14 16:35:45.330311 WARNING ------------------------------------------------------------
2020-06-14 16:35:45.330992 WARNING Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/appdaemon/admain.py", line 82, in run
    self.rundash = rundash.RunDash(self.AD, loop, self.logger, self.access, **hadashboard)
  File "/usr/local/lib/python3.6/site-packages/appdaemon/rundash.py", line 130, in __init__
    dash_net = url.netloc.split(":")
TypeError: a bytes-like object is required, not 'str'

2020-06-14 16:35:45.331065 WARNING ------------------------------------------------------------
2020-06-14 16:35:45.331140 INFO AppDeamon Exited

**Comment by billimek** [comment]
Hi @rwlove, I didn't add this feature but believe that there are a couple of possible problems:

1. It looks like the `DASH_URL` environment variable (required by appDaemon?) isn't being set unless [ingress is enabled](https://github.com/billimek/billimek-charts/blob/master/charts/home-assistant/templates/deployment.yaml#L315-L319).
1. Similarly, the `TOKEN` environment variable is not set due to the `haToken` value not being set with the helm chart configuration and thus the appDaemon doesn't have a token to [reference at runtime](https://github.com/billimek/billimek-charts/blob/master/charts/home-assistant/templates/deployment.yaml#L320-L326).

Can you try enabling ingress and/or setting a token value in the helm configuration to see if this helps?

**Comment by rwlove** [comment]
The below changes to my values.yaml seems to allow it to work. 
```
@@ -278,7 +281,7 @@
     # nodePort: 30000
 
 appdaemon:
-  enabled: false
+  enabled: true
 
   ## code-server container image
   ##
@@ -288,7 +291,7 @@
     pullPolicy: IfNotPresent
 
   ## Home Assistant API token
-  # haToken:
+  haToken: <MY_TOKEN_FROM_WEBUI>
 
   ## Additional hass-vscode container environment variable
   ## For instance to add a http_proxy
@@ -296,7 +299,7 @@
   extraEnv: {}
 
   ingress:
-    enabled: false
+    enabled: true
     annotations: {}
       # kubernetes.io/ingress.class: nginx
       # kubernetes.io/tls-acme: "true"
```

It generates the following appdaemon.yaml file:
```
log:
  logfile: STDOUT
  errorfile: STDERR
appdaemon:
  threads: 10
  plugins:
    HASS:
      type: hass
      ha_url: http://localhost:8123
      token: <MY_TOKEN_FROM_WEBUI>
hadashboard:
  dash_url: http://0.0.0.0:5050
```

Can you help me understand how the appdaemon.yaml file gets generated? For example when I grep for “errorfile” which is in the resultant appdaemon.yaml, I don’t get any hits in your repository.

I’d love to upgrade this chart to make use of appdaemon 4.0.3 (currently using 3.0.5). I got it to work by manually updating the appdaemon.yaml file on my persistent storage and rebooting, but if I understood how the appdaemon.yaml file is being generated I could probably provide a patch to update the appdaemon version. Here’s an example of how the resultant appdaemon.yaml file should look when using 4.0.3.

```
appdaemon:
  threads: 10
  latitude: 15
  longitude: 31
  elevation: 45
  time_zone: 'America/Los_Angeles'
  plugins:
    HASS:
      type: hass
      ha_url: http://localhost:8123
      token: <MY_TOKEN_FROM_WEBUI>
hadashboard:
http:
  url: http://0.0.0.0:5050
admin:
api:
```

Do you know where the user is supposed to provide the appdaemon.cfg file?

Lastly, I’m a bit confused about where to get the token from. I did this last weekend, but I believe I started Home Assistant once, went to the webui, generated the token, added that token to the helm chart values.yaml and restarted Home Assistant. Do you know if this is the right procedure?
