### ISSUE TITLE
Simplify promtail config for plex

### ISSUE THREAD

**Issue by onedr0p** [billimek/billimek-charts#341]
There is a error with 1.8.0 when enabled logging w/ promtail

```
[helm-operator-6c987bc645-jpnwd] ts=2020-08-28T14:36:25.700553474Z caller=release.go:294 component=release release=plex targetNamespace=default resource=default:helmrelease/plex helmVersion=v3 error="dry-run upgrade for comparison failed: YAML parse error on plex/templates/deployment.yaml: error converting YAML to JSON: yaml: line 31: mapping values are not allowed in this context" phase=dry-run-compare
```

I think it might be better anyways to make the options less configurable...

# before

```
logging:
  promtail:
    enabled: false
    image:
      repository: grafana/promtail
      tag: 1.6.0
      pullPolicy: IfNotPresent
    config:
      server:
        disable: true
      positions:
        filename: /tmp/positions.yaml
      clients:
        - url: http://loki.logs.svc.cluster.local:3100/loki/api/v1/push
      scrape_configs:
      - job_name: plex-logs
        static_configs:
        - targets:
            - localhost
          labels:
            job: plex-logs
            __path__: "/plex-logs/*.log"
      - job_name: plex-plugin-logs
        static_configs:
        - targets:
            - localhost
          labels:
            job: plex-plugin-logs
            __path__: "/plex-logs/PMS Plugin Logs/*.log"
```

# after

```
logging:
  promtail:
    enabled: false
    image:
      repository: grafana/promtail
      tag: 1.6.0
      pullPolicy: IfNotPresent
    lokiUrl: http://loki.logs.svc.cluster.local:3100/loki/api/v1/push
```

This would make less clutter in the values and in our helm releases.
